// NIST SP 800-53 Rev 5 — Complete Control Families
export const FAMILIES = [
  { id: "AC", name: "Access Control", nameTW: "存取控制", desc: "管控系統存取權限，包含帳號管理、存取執行、最小權限、遠端存取、無線存取、行動裝置等控制機制。" },
  { id: "AT", name: "Awareness and Training", nameTW: "安全意識與訓練", desc: "確保使用和建立資訊系統的人員接受適當的安全與隱私意識培訓及角色基礎訓練。" },
  { id: "AU", name: "Audit and Accountability", nameTW: "稽核與問責", desc: "涵蓋稽核日誌的產生、審查、保護、保留，以及不可否認性與跨組織稽核等機制。" },
  { id: "CA", name: "Assessment, Authorization, and Monitoring", nameTW: "評估、授權與監控", desc: "安全與隱私控制之評估、系統授權、持續監控、滲透測試及行動計畫之管理。" },
  { id: "CM", name: "Configuration Management", nameTW: "組態管理", desc: "系統基線組態的建立、變更控制、元件清冊、軟體限制及組態設定之管理。" },
  { id: "CP", name: "Contingency Planning", nameTW: "應變計畫", desc: "涵蓋業務持續運作、災難復原、系統備份、替代場所與通訊之應變準備。" },
  { id: "IA", name: "Identification and Authentication", nameTW: "識別與鑑別", desc: "管理使用者與裝置的身分識別、鑑別器（密碼、憑證、多因子等）及身分驗證。" },
  { id: "IR", name: "Incident Response", nameTW: "事件回應", desc: "事件處理、報告、監控、測試及回應計畫之建立與維護。" },
  { id: "MA", name: "Maintenance", nameTW: "維護", desc: "系統與元件的受控維護、遠端維護、維護工具管控及維護人員管理。" },
  { id: "MP", name: "Media Protection", nameTW: "媒體保護", desc: "管控儲存媒體的存取、標記、儲存、運送、消毒與使用。" },
  { id: "PE", name: "Physical and Environmental Protection", nameTW: "實體與環境保護", desc: "實體存取控制、環境控制、電力保護、消防、水害防護及資產監控。" },
  { id: "PL", name: "Planning", nameTW: "規劃", desc: "系統安全與隱私計畫的制定、行為規則、安全架構及基線選擇。" },
  { id: "PM", name: "Program Management", nameTW: "計畫管理", desc: "組織層級之資安與隱私計畫管理，涵蓋風險策略、人力、威脅意識、供應鏈策略等。" },
  { id: "PS", name: "Personnel Security", nameTW: "人員安全", desc: "人員篩選、職位風險指定、離職/調動處理、存取協議及人員制裁。" },
  { id: "PT", name: "PII Processing and Transparency", nameTW: "個資處理與透明度", desc: "Rev 5 新增，管控個人可識別資訊之處理授權、目的限制、同意、隱私通知等。", isNew: true },
  { id: "RA", name: "Risk Assessment", nameTW: "風險評估", desc: "安全分類、風險評估執行、弱點掃描、威脅獵捕及隱私影響評估。" },
  { id: "SA", name: "System and Services Acquisition", nameTW: "系統與服務取得", desc: "系統開發生命週期、取得流程、外部服務、供應鏈保護、開發者安全等控制。" },
  { id: "SC", name: "System and Communications Protection", nameTW: "系統與通訊保護", desc: "邊界保護、加密、傳輸安全、會話管理、行程隔離、DNS 安全等廣泛之系統通訊保護控制。" },
  { id: "SI", name: "System and Information Integrity", nameTW: "系統與資訊完整性", desc: "漏洞修補、惡意程式碼防護、系統監控、輸入驗證、錯誤處理、去識別化等控制。" },
  { id: "SR", name: "Supply Chain Risk Management", nameTW: "供應鏈風險管理", desc: "Rev 5 新增，涵蓋供應鏈控制流程、來源追溯、供應商評估、防篡改與元件真偽性等。", isNew: true },
];

// Baseline bitmask: 1=Low, 2=Moderate, 4=High, 8=Privacy
// Format: [id, name, nameTW, baselineBitmask, description]
const RAW = [
  // ── AC ──
  ["AC-1","Policy and Procedures","政策與程序",15,"制定、記錄並傳達存取控制政策與程序，涵蓋目的、範圍、角色、職責、管理承諾、組織實體間之協調及合規性。"],
  ["AC-2","Account Management","帳號管理",7,"定義允許與禁止之帳號類型；指派帳號管理員；要求群組與角色成員資格之前提條件；授權使用者、群組、角色及存取授權。"],
  ["AC-3","Access Enforcement","存取強制執行",7,"依據適用之存取控制政策，強制執行對資訊與系統資源之已核准邏輯存取授權。"],
  ["AC-4","Information Flow Enforcement","資訊流控制",6,"依據組織定義之資訊流控制政策，強制執行系統內部及連接系統間之已核准資訊流授權。"],
  ["AC-5","Separation of Duties","職責分離",6,"識別並記錄需要分離之職責；定義系統存取授權以支援職責分離。"],
  ["AC-6","Least Privilege","最小權限",6,"採用最小權限原則，僅允許使用者（或代表使用者行事之行程）執行組織任務所必需之已授權存取。"],
  ["AC-7","Unsuccessful Logon Attempts","登入失敗嘗試",7,"在特定時間內限制連續無效登入嘗試次數；自動鎖定帳號/節點、延遲下次登入提示，或依組織定義採取行動。"],
  ["AC-8","System Use Notification","系統使用通知",7,"在授予系統存取前向使用者顯示系統使用通知，提供與適用法律一致之隱私與安全告知。"],
  ["AC-9","Previous Logon Notification","先前登入通知",0,"成功登入系統時通知使用者上次登入的日期與時間。"],
  ["AC-10","Concurrent Session Control","並行工作階段控制",4,"限制每個帳號/帳號類型之並行工作階段數量。"],
  ["AC-11","Device Lock","裝置鎖定",6,"在閒置指定時間後啟動裝置鎖定或要求使用者主動鎖定；保持鎖定直到使用者透過識別與鑑別程序重新建立存取。"],
  ["AC-12","Session Termination","工作階段終止",6,"在組織定義之條件或觸發事件發生後，自動終止使用者工作階段。"],
  ["AC-14","Permitted Actions Without Identification or Authentication","無需識別或鑑別之允許動作",7,"識別可在無需識別或鑑別下對系統執行的使用者動作；在安全計畫中記錄並提供支持理由。"],
  ["AC-16","Security and Privacy Attributes","安全與隱私屬性",0,"提供將安全與隱私屬性與屬性值相關聯之方法，適用於儲存中、處理中及/或傳輸中之資訊。"],
  ["AC-17","Remote Access","遠端存取",7,"建立並記錄每種允許之遠端存取類型的使用限制、組態/連線要求與實施指引；在允許連線前授權每種遠端存取類型。"],
  ["AC-18","Wireless Access","無線存取",7,"建立每種無線存取類型之組態要求、連線要求與實施指引；在允許連線前授權每種無線存取類型。"],
  ["AC-19","Access Control for Mobile Devices","行動裝置存取控制",7,"建立組織控制行動裝置之組態要求、連線要求與實施指引（含裝置在受控區域外時）；授權行動裝置連接組織系統。"],
  ["AC-20","Use of External Systems","外部系統使用",7,"建立條款與條件或識別已聲明之控制措施，與擁有/營運外部系統之組織建立信任關係。"],
  ["AC-21","Information Sharing","資訊分享",6,"使授權使用者能判斷分享夥伴之存取授權是否符合資訊的存取與使用限制；採用自動化機制協助決策。"],
  ["AC-22","Publicly Accessible Content","公開可存取內容",7,"指定授權公開資訊之人員；訓練確保公開資訊不含非公開資訊；張貼前審查；定期審查已公開內容。"],
  ["AC-23","Data Mining Protection","資料探勘保護",0,"對組織定義之資料儲存物件採用技術，以偵測並防範未授權之資料探勘。"],
  ["AC-24","Access Control Decisions","存取控制決策",0,"建立程序或實施機制，確保在存取強制執行前，對每個存取請求套用存取控制決策。"],
  ["AC-25","Reference Monitor","參考監視器",0,"為存取控制政策實施參考監視器，使其防篡改、始終被調用，且小到足以進行完整性可保證之分析與測試。"],
  // ── AT ──
  ["AT-1","Policy and Procedures","政策與程序",15,"制定、記錄並傳達安全意識與訓練政策及程序。"],
  ["AT-2","Literacy Training and Awareness","素養訓練與意識",15,"為系統使用者提供安全與隱私素養訓練：新使用者初始訓練及定期複訓；系統變更或特定事件後之訓練。"],
  ["AT-3","Role-based Training","角色基礎訓練",15,"在授權存取系統前及定期為具特定角色與職責之人員提供角色基礎安全與隱私訓練。"],
  ["AT-4","Training Records","訓練記錄",15,"記錄並監控資訊安全與隱私訓練活動；保留個人訓練記錄至組織定義之期間。"],
  ["AT-6","Training Feedback","訓練回饋",0,"以組織定義之頻率向組織定義之人員提供組織訓練結果之回饋。"],
  // ── AU ──
  ["AU-1","Policy and Procedures","政策與程序",15,"制定、記錄並傳達稽核與問責政策及程序。"],
  ["AU-2","Event Logging","事件日誌記錄",15,"識別系統能夠記錄之事件類型；與需要稽核資訊之組織實體協調事件日誌記錄功能。"],
  ["AU-3","Content of Audit Records","稽核記錄內容",7,"確保稽核記錄包含：事件類型、發生時間/地點、來源、結果，及相關身分識別。"],
  ["AU-4","Audit Log Storage Capacity","稽核日誌儲存容量",7,"配置足夠的稽核日誌儲存容量以容納組織定義之保留要求。"],
  ["AU-5","Response to Audit Logging Process Failures","稽核日誌處理失敗之回應",7,"在稽核日誌處理失敗時於定義時間內警告指定人員；採取額外行動。"],
  ["AU-6","Audit Record Review, Analysis, and Reporting","稽核記錄審查、分析與報告",7,"以定義頻率審查並分析系統稽核記錄，尋找不當或異常活動跡象及潛在影響。"],
  ["AU-7","Audit Record Reduction and Report Generation","稽核記錄精簡與報告產生",6,"提供稽核記錄精簡與報告產生能力，支援隨需稽核審查及事後調查。"],
  ["AU-8","Time Stamps","時間戳記",7,"使用內部系統時鐘為稽核記錄產生時間戳記；使用 UTC 或含時區偏移。"],
  ["AU-9","Protection of Audit Information","稽核資訊保護",7,"保護稽核資訊與工具免受未授權之存取、修改與刪除。"],
  ["AU-10","Non-repudiation","不可否認性",4,"提供不可否認之證據，證明個人（或代表行事之行程）已執行定義之行動。"],
  ["AU-11","Audit Record Retention","稽核記錄保留",15,"保留稽核記錄以支援事後調查並符合法規與組織資訊保留要求。"],
  ["AU-12","Audit Record Generation","稽核記錄產生",7,"在定義之系統元件上為 AU-2 所定義之事件類型提供稽核記錄產生能力。"],
  ["AU-13","Monitoring for Information Disclosure","資訊揭露監控",0,"監控開源資訊及/或資訊站點，尋找組織資訊未授權揭露之證據。"],
  ["AU-14","Session Audit","工作階段稽核",0,"提供對使用者工作階段內容進行記錄/檢視/聽取/日誌記錄之能力。"],
  ["AU-16","Cross-organizational Audit Logging","跨組織稽核日誌",0,"當稽核資訊跨組織邊界傳輸時，採用定義方法協調外部組織間之稽核資訊。"],
  // ── CA ──
  ["CA-1","Policy and Procedures","政策與程序",15,"制定、記錄並傳達評估、授權與監控政策及程序。"],
  ["CA-2","Control Assessments","控制評估",15,"選擇適當評估員；制定控制評估計畫；確保評估獨立性。"],
  ["CA-3","Information Exchange","資訊交換",7,"使用互連安全協議、備忘錄等核准並管理系統間之資訊交換。"],
  ["CA-5","Plan of Action and Milestones","行動計畫與里程碑",15,"制定系統行動計畫與里程碑以記錄計畫性矯正行動；定期更新。"],
  ["CA-6","Authorization","授權",15,"指派高階官員為系統授權官員；確保授權官員在系統運作前接受並授權系統運作。"],
  ["CA-7","Continuous Monitoring","持續監控",15,"制定系統層級持續監控策略並依組織層級策略實施；建立系統層級監控指標與頻率。"],
  ["CA-8","Penetration Testing","滲透測試",4,"以組織定義之頻率對定義之系統或系統元件執行滲透測試。"],
  ["CA-9","Internal System Connections","內部系統連接",7,"授權內部元件連接至系統；記錄介面特性、安全與隱私要求；定期審查持續需求。"],
  // ── CM ──
  ["CM-1","Policy and Procedures","政策與程序",15,"制定、記錄並傳達組態管理政策及程序。"],
  ["CM-2","Baseline Configuration","基線組態",7,"開發、記錄並維護系統的當前基線組態。"],
  ["CM-3","Configuration Change Control","組態變更控制",6,"透過組態控制委員會判定變更類型；審查提議的變更並核准/不核准；記錄變更決定。"],
  ["CM-4","Impact Analyses","影響分析",7,"在實施變更前分析對系統之影響，以判定潛在的安全與隱私影響。"],
  ["CM-5","Access Restrictions for Change","變更存取限制",6,"定義、記錄、核准並強制執行與系統變更相關之實體與邏輯存取限制。"],
  ["CM-6","Configuration Settings","組態設定",7,"使用反映最嚴格模式之組態設定建立並記錄系統元件之組態設定。"],
  ["CM-7","Least Functionality","最小功能",7,"配置系統僅提供任務必要能力；限制或禁止使用定義之功能、連接埠、協定、軟體及/或服務。"],
  ["CM-8","System Component Inventory","系統元件清冊",7,"開發並記錄系統元件清冊，準確反映系統；與系統邊界內元件授權一致。"],
  ["CM-9","Configuration Management Plan","組態管理計畫",6,"制定、記錄並實施系統之組態管理計畫，涵蓋角色、職責、流程與程序。"],
  ["CM-10","Software Usage Restrictions","軟體使用限制",7,"依據軟體合約與版權法使用軟體與相關文件；追蹤受數量授權保護之軟體。"],
  ["CM-11","User-installed Software","使用者安裝軟體",7,"建立使用者安裝軟體之管理政策；強制執行軟體安裝政策；監控合規性。"],
  ["CM-12","Information Location","資訊位置",6,"識別並記錄定義之資訊的位置及處理該資訊之特定系統元件。"],
  ["CM-13","Data Action Mapping","資料行為映射",8,"建立並記錄組織已識別之有問題資料行為的映射。"],
  ["CM-14","Signed Components","簽章元件",4,"防止安裝未經驗證軟體與韌體簽章之元件。"],
  // ── CP ──
  ["CP-1","Policy and Procedures","政策與程序",15,"制定、記錄並傳達應變計畫政策及程序。"],
  ["CP-2","Contingency Plan","應變計畫",7,"制定系統應變計畫，識別重要任務與業務功能及相關應變需求。"],
  ["CP-3","Contingency Training","應變訓練",7,"在指派角色後及定期為應變人員提供應變訓練。"],
  ["CP-4","Contingency Plan Testing","應變計畫測試",7,"以定義之頻率使用定義之測試方法測試應變計畫以判定有效性及準備度。"],
  ["CP-6","Alternate Storage Site","替代儲存場所",6,"建立含必要協議之替代儲存場所，允許儲存並擷取系統備份資訊。"],
  ["CP-7","Alternate Processing Site","替代處理場所",6,"建立含必要協議之替代處理場所以恢復任務與業務功能操作。"],
  ["CP-8","Telecommunications Services","電信服務",6,"建立替代電信服務以允許持續進行重要任務與業務功能操作。"],
  ["CP-9","System Backup","系統備份",7,"以定義之頻率進行使用者層級、系統層級及系統文件之備份。"],
  ["CP-10","System Recovery and Reconstitution","系統復原與重建",7,"提供在中斷、妥協或失效後將系統復原與重建至已知狀態之能力。"],
  ["CP-11","Alternate Communications Protocols","替代通訊協定",0,"提供使用替代通訊協定以支援維持操作持續性之能力。"],
  ["CP-12","Safe Mode","安全模式",0,"當定義之條件被偵測到時，系統在安全模式下運作。"],
  ["CP-13","Alternative Security Mechanisms","替代安全機制",0,"當主要安全機制不可用時，採用替代或補充安全機制。"],
  // ── IA ──
  ["IA-1","Policy and Procedures","政策與程序",15,"制定、記錄並傳達識別與鑑別政策及程序。"],
  ["IA-2","Identification and Authentication (Organizational Users)","組織使用者識別與鑑別",7,"唯一識別並鑑別組織使用者及代表組織使用者行事之行程。"],
  ["IA-3","Device Identification and Authentication","裝置識別與鑑別",6,"在建立系統連線前，唯一識別並鑑別定義之裝置及/或裝置類型。"],
  ["IA-4","Identifier Management","識別碼管理",7,"透過授權指派識別碼來管理；防止重複使用；閒置後停用。"],
  ["IA-5","Authenticator Management","鑑別器管理",7,"透過驗證接收初始鑑別器之身分來管理鑑別器；確保足夠的機制強度。"],
  ["IA-6","Authentication Feedback","鑑別回饋",7,"在鑑別過程中模糊鑑別資訊的回饋，以保護資訊免於利用。"],
  ["IA-7","Cryptographic Module Authentication","密碼模組鑑別",7,"實施符合適用法律之密碼模組鑑別機制。"],
  ["IA-8","Identification and Authentication (Non-organizational Users)","非組織使用者識別與鑑別",7,"唯一識別並鑑別非組織使用者或代表其行事之行程。"],
  ["IA-9","Service Identification and Authentication","服務識別與鑑別",0,"使用安全保護措施識別並鑑別定義之系統服務與應用程式。"],
  ["IA-10","Adaptive Authentication","自適應鑑別",0,"要求使用者採用與定義情況相適應之鑑別。"],
  ["IA-11","Re-authentication","重新鑑別",7,"要求使用者在定義之情況或情境下重新鑑別。"],
  ["IA-12","Identity Proofing","身分驗證",7,"以定義之等級進行身分驗證以接收帳號與鑑別器。"],
  // ── IR ──
  ["IR-1","Policy and Procedures","政策與程序",15,"制定、記錄並傳達事件回應政策及程序。"],
  ["IR-2","Incident Response Training","事件回應訓練",7,"在擔任事件回應角色後及定期提供系統相關事件回應訓練。"],
  ["IR-3","Incident Response Testing","事件回應測試",6,"以定義之頻率測試事件回應能力以判定有效性。"],
  ["IR-4","Incident Handling","事件處理",7,"實施事件處理能力：準備、偵測與分析、遏制、根除與復原。"],
  ["IR-5","Incident Monitoring","事件監控",7,"追蹤並記錄系統安全與隱私事件。"],
  ["IR-6","Incident Reporting","事件報告",15,"要求人員在定義時間內報告可疑事件；向定義之機關報告事件資訊。"],
  ["IR-7","Incident Response Assistance","事件回應協助",7,"提供對使用者可用之事件回應支援資源，為事件的處理與報告提供諮詢與協助。"],
  ["IR-8","Incident Response Plan","事件回應計畫",7,"制定事件回應計畫，提供組織實施其事件回應能力之路線圖。"],
  ["IR-9","Information Spillage Response","資訊溢出回應",0,"透過識別受污染之資訊、系統或元件來回應資訊溢出。"],
  ["IR-10","Integrated Information Security Analysis Team","整合資安分析團隊",0,"建立可部署之整合資訊安全分析團隊以調查定義之安全問題或事件。"],
  // ── MA ──
  ["MA-1","Policy and Procedures","政策與程序",7,"制定、記錄並傳達維護政策及程序。"],
  ["MA-2","Controlled Maintenance","受控維護",7,"依據規格排程、記錄並審查系統元件的維護、修理與更換記錄。"],
  ["MA-3","Maintenance Tools","維護工具",6,"核准、控制並監控維護工具之使用。"],
  ["MA-4","Nonlocal Maintenance","非本地維護",7,"核准並監控非本地維護與診斷活動；完成後終止工作階段與連線。"],
  ["MA-5","Maintenance Personnel","維護人員",7,"建立維護人員授權流程；維護授權人員清單。"],
  ["MA-6","Timely Maintenance","及時維護",6,"取得定義之系統元件的備用零件與維護支援。"],
  ["MA-7","Field Maintenance","現場維護",0,"將定義之系統元件限制在現場維護修理而非移除至維護設施。"],
  // ── MP ──
  ["MP-1","Policy and Procedures","政策與程序",15,"制定、記錄並傳達媒體保護政策及程序。"],
  ["MP-2","Media Access","媒體存取",7,"限制對定義之數位及/或非數位媒體類型之存取。"],
  ["MP-3","Media Marking","媒體標記",6,"標記包含定義資訊類型之系統媒體，指示分發限制與安全標記。"],
  ["MP-4","Media Storage","媒體儲存",6,"在定義之受控區域內實體控制並安全儲存定義之媒體類型。"],
  ["MP-5","Media Transport","媒體運送",6,"使用安全保護措施保護並控制定義之媒體類型在受控區域外的運送。"],
  ["MP-6","Media Sanitization","媒體消毒",7,"在處置、釋出或再使用前消毒定義之系統媒體。"],
  ["MP-7","Media Use","媒體使用",7,"使用安全保護措施限制定義之系統媒體類型之使用。"],
  ["MP-8","Media Downgrading","媒體降級",0,"依據定義之標準與政策建立系統媒體降級流程。"],
  // ── PE ──
  ["PE-1","Policy and Procedures","政策與程序",15,"制定、記錄並傳達實體與環境保護政策及程序。"],
  ["PE-2","Physical Access Authorizations","實體存取授權",7,"制定、核准並維護被授權實體存取設施之人員清單。"],
  ["PE-3","Physical Access Control","實體存取控制",7,"在入口/出口點強制執行實體存取授權。"],
  ["PE-4","Access Control for Transmission","傳輸存取控制",6,"控制對系統分配與佈線區域之實體存取。"],
  ["PE-5","Access Control for Output Devices","輸出裝置存取控制",6,"控制對輸出裝置之實體存取，防止未授權查看輸出。"],
  ["PE-6","Monitoring Physical Access","實體存取監控",7,"監控對系統設施的實體存取以偵測並回應安全事件。"],
  ["PE-8","Visitor Access Records","訪客存取記錄",7,"維護訪客存取記錄。"],
  ["PE-9","Power Equipment and Cabling","電力設備與佈線",6,"保護系統電力設備與佈線免受損害與破壞。"],
  ["PE-10","Emergency Shutoff","緊急關閉",6,"提供在緊急情況下關閉系統或個別元件之能力。"],
  ["PE-11","Emergency Power","緊急電力",6,"提供備援電源以促進有序關閉/轉換。"],
  ["PE-12","Emergency Lighting","緊急照明",7,"採用並維護自動啟動之緊急照明系統。"],
  ["PE-13","Fire Protection","消防保護",7,"採用並維護滅火與偵測裝置/系統。"],
  ["PE-14","Environmental Controls","環境控制",7,"維護可接受範圍內之溫度與濕度水平。"],
  ["PE-15","Water Damage Protection","水害保護",7,"透過提供主水閘閥或隔離閥保護系統免受水害。"],
  ["PE-16","Delivery and Removal","交付與移除",7,"授權、監控並控制系統元件進出設施。"],
  ["PE-17","Alternate Work Site","替代工作場所",6,"在替代工作場所實施安全控制措施。"],
  ["PE-18","Location of System Components","系統元件位置",0,"將系統元件置於設施內以最小化危害。"],
  ["PE-19","Information Leakage","資訊洩漏",0,"保護系統免受電磁信號散射造成之資訊洩漏。"],
  ["PE-20","Asset Monitoring and Tracking","資產監控與追蹤",0,"追蹤並監控組織資產之位置與移動。"],
  ["PE-21","Electromagnetic Pulse Protection","電磁脈衝保護",0,"採用防護技術以防止電磁脈衝損害。"],
  ["PE-22","Component Marking","元件標記",0,"標記系統硬體元件以指示影響或分類等級。"],
  ["PE-23","Facility Location","設施位置",0,"根據要求規劃處理設施之位置或場地。"],
  // ── PL ──
  ["PL-1","Policy and Procedures","政策與程序",15,"制定、記錄並傳達規劃政策及程序。"],
  ["PL-2","System Security and Privacy Plans","系統安全與隱私計畫",15,"制定系統安全與隱私計畫。"],
  ["PL-4","Rules of Behavior","行為規則",15,"建立可接受使用行為規則與限制。"],
  ["PL-7","Concept of Operations","作業概念",0,"制定系統之作業概念。"],
  ["PL-8","Security and Privacy Architectures","安全與隱私架構",7,"制定安全與隱私架構。"],
  ["PL-9","Central Management","集中管理",0,"集中管理定義之控制措施。"],
  ["PL-10","Baseline Selection","基線選擇",7,"為系統選擇控制基線。"],
  ["PL-11","Baseline Tailoring","基線裁切",7,"裁切選定之控制基線。"],
  // ── PM ──
  ["PM-1","Information Security Program Plan","資訊安全計畫方案",8,"制定並傳達全組織資訊安全計畫方案。"],
  ["PM-2","Information Security Program Leadership Role","資訊安全計畫領導角色",8,"指派高階資訊安全官員。"],
  ["PM-3","Information Security and Privacy Resources","資訊安全與隱私資源",8,"將規劃所需資源納入資本規劃。"],
  ["PM-4","Plan of Action and Milestones Process","行動計畫與里程碑流程",8,"實施行動計畫與里程碑流程。"],
  ["PM-5","System Inventory","系統清冊",8,"開發並維護組織系統清冊。"],
  ["PM-6","Measures of Performance","績效衡量",8,"制定、監控並報告績效衡量指標。"],
  ["PM-7","Enterprise Architecture","企業架構",8,"制定並維護企業架構。"],
  ["PM-8","Critical Infrastructure Plan","關鍵基礎設施計畫",0,"保護關鍵基礎設施。"],
  ["PM-9","Risk Management Strategy","風險管理策略",8,"制定全面風險管理策略。"],
  ["PM-10","Authorization Process","授權流程",8,"管理系統之授權狀態。"],
  ["PM-11","Mission and Business Process Definition","任務與業務流程定義",8,"定義組織任務與業務流程。"],
  ["PM-12","Insider Threat Program","內部威脅計畫",0,"實施內部威脅計畫。"],
  ["PM-13","Security and Privacy Workforce","安全與隱私人力",8,"建立人力發展與改善計畫。"],
  ["PM-14","Testing, Training, and Monitoring","測試、訓練與監控",8,"實施測試、訓練與監控流程。"],
  ["PM-15","Security and Privacy Groups and Associations","安全與隱私團體及協會",0,"與安全與隱私團體建立聯繫。"],
  ["PM-16","Threat Awareness Program","威脅意識計畫",0,"實施威脅意識計畫。"],
  ["PM-17","Protecting CUI on External Systems","外部系統之 CUI 保護",0,"管理外部系統上 CUI 保護。"],
  ["PM-18","Privacy Program Plan","隱私計畫方案",8,"制定並傳達全組織隱私計畫方案。"],
  ["PM-19","Privacy Program Leadership Role","隱私計畫領導角色",8,"指派高階隱私官員。"],
  ["PM-20","Dissemination of Privacy Program Information","隱私計畫資訊傳播",8,"維護公開管道提供隱私計畫資訊。"],
  ["PM-21","Accounting of Disclosures","揭露之會計",8,"建立揭露之會計。"],
  ["PM-22","PII Quality Management","個資品質管理",8,"確保個資品質。"],
  ["PM-23","Data Governance Body","資料治理機構",8,"建立資料治理機構。"],
  ["PM-24","Data Integrity Board","資料完整性委員會",8,"建立資料完整性委員會。"],
  ["PM-25","Minimization of PII in Testing/Training/Research","測試訓練研究中個資最小化",8,"最小化測試訓練研究中個資。"],
  ["PM-26","Complaint Management","申訴管理",8,"接收並回應隱私投訴。"],
  ["PM-27","Privacy Reporting","隱私報告",8,"制定隱私報告。"],
  ["PM-28","Risk Framing","風險框架",0,"識別產生風險之假設與限制。"],
  ["PM-29","Risk Management Program Leadership Roles","風險管理計畫領導角色",0,"指定高階官員管理風險管理流程。"],
  ["PM-30","Supply Chain Risk Management Strategy","供應鏈風險管理策略",0,"制定供應鏈風險管理策略。"],
  ["PM-31","Continuous Monitoring Strategy","持續監控策略",0,"制定持續監控策略。"],
  ["PM-32","Purposing","目的界定",8,"識別處理個資時之組織目的。"],
  // ── PS ──
  ["PS-1","Policy and Procedures","政策與程序",15,"制定、記錄並傳達人員安全政策及程序。"],
  ["PS-2","Position Risk Designation","職位風險指定",7,"為所有職位指定風險等級。"],
  ["PS-3","Personnel Screening","人員篩選",7,"在授權存取前篩選人員。"],
  ["PS-4","Personnel Termination","人員離職",15,"在離職時停用存取、終止憑證、收回財產。"],
  ["PS-5","Personnel Transfer","人員調動",7,"在調動時審查持續存取授權需求。"],
  ["PS-6","Access Agreements","存取協議",15,"制定存取協議；確保簽署。"],
  ["PS-7","External Personnel Security","外部人員安全",7,"建立外部服務提供者之人員安全要求。"],
  ["PS-8","Personnel Sanctions","人員制裁",7,"對未遵循政策之個人採用制裁流程。"],
  ["PS-9","Position Descriptions","職位說明",0,"將安全與隱私角色職責納入職位說明。"],
  // ── PT ──
  ["PT-1","Policy and Procedures","政策與程序",15,"制定、記錄並傳達個資處理與透明度政策及程序。"],
  ["PT-2","Authority to Process PII","處理個資之授權",8,"判定並記錄處理個資之法律授權。"],
  ["PT-3","PII Processing Purposes","個資處理目的",8,"識別並記錄處理個資之目的。"],
  ["PT-4","Consent","同意",8,"在處理個資前取得個人同意。"],
  ["PT-5","Privacy Notice","隱私通知",8,"向個人提供有效的隱私通知。"],
  ["PT-6","System of Records Notice","記錄系統通知",8,"發布記錄系統通知。"],
  ["PT-7","Specific Categories of PII","特定類別個資",8,"對特定類別個資適用特別處理。"],
  ["PT-8","Computer Matching Requirements","電腦比對要求",8,"確保電腦比對符合法律要求。"],
  // ── RA ──
  ["RA-1","Policy and Procedures","政策與程序",15,"制定、記錄並傳達風險評估政策及程序。"],
  ["RA-2","Security Categorization","安全分類",15,"對系統與資訊進行安全分類。"],
  ["RA-3","Risk Assessment","風險評估",15,"進行風險評估以識別威脅與風險。"],
  ["RA-5","Vulnerability Monitoring and Scanning","弱點監控與掃描",7,"監控並掃描系統弱點。"],
  ["RA-6","Technical Surveillance Countermeasures Survey","技術監控反制調查",0,"進行技術監控反制調查。"],
  ["RA-7","Risk Response","風險回應",15,"依據風險容忍度回應發現的風險。"],
  ["RA-8","Privacy Impact Assessments","隱私影響評估",8,"進行隱私影響評估。"],
  ["RA-9","Criticality Analysis","關鍵性分析",4,"識別關鍵系統元件與功能。"],
  ["RA-10","Threat Hunting","威脅獵捕",0,"進行威脅獵捕活動。"],
  // ── SA ──
  ["SA-1","Policy and Procedures","政策與程序",15,"制定、記錄並傳達系統與服務取得政策及程序。"],
  ["SA-2","Allocation of Resources","資源配置",15,"將保護所需資源納入規劃。"],
  ["SA-3","System Development Life Cycle","系統開發生命週期",15,"使用含安全與隱私考量之 SDLC。"],
  ["SA-4","Acquisition Process","取得流程",15,"在合約中含入安全與隱私要求。"],
  ["SA-5","System Documentation","系統文件",7,"取得或制定系統文件。"],
  ["SA-8","Security and Privacy Engineering Principles","安全與隱私工程原則",15,"套用安全與隱私工程原則。"],
  ["SA-9","External System Services","外部系統服務",15,"要求外部服務提供者遵循安全與隱私要求。"],
  ["SA-10","Developer Configuration Management","開發者組態管理",6,"要求開發者執行組態管理。"],
  ["SA-11","Developer Testing and Evaluation","開發者測試與評估",6,"要求開發者測試與評估。"],
  ["SA-15","Development Process, Standards, and Tools","開發流程、標準與工具",6,"要求開發者遵循開發流程。"],
  ["SA-16","Developer-provided Training","開發者提供之訓練",0,"要求開發者提供訓練。"],
  ["SA-17","Developer Security and Privacy Architecture and Design","開發者安全與隱私架構及設計",4,"要求開發者產生安全架構。"],
  ["SA-20","Customized Development of Critical Components","關鍵元件客製開發",0,"客製開發關鍵系統元件。"],
  ["SA-21","Developer Screening","開發者篩選",0,"要求開發者滿足篩選標準。"],
  ["SA-22","Unsupported System Components","不受支援之系統元件",7,"替換不再受支援之元件。"],
  ["SA-23","Specialization","專門化",0,"採用專門化以增加可信度。"],
  // ── SC ──
  ["SC-1","Policy and Procedures","政策與程序",15,"制定、記錄並傳達系統與通訊保護政策及程序。"],
  ["SC-2","Separation of System and User Functionality","系統與使用者功能分離",6,"將使用者功能與系統管理功能分離。"],
  ["SC-3","Security Function Isolation","安全功能隔離",4,"將安全功能與非安全功能隔離。"],
  ["SC-4","Information in Shared System Resources","共享系統資源中之資訊",6,"防止透過共享資源之未授權資訊轉移。"],
  ["SC-5","Denial-of-service Protection","阻斷服務保護",7,"保護或限制 DoS 攻擊影響。"],
  ["SC-7","Boundary Protection","邊界保護",7,"監控並控制通訊邊界。"],
  ["SC-8","Transmission Confidentiality and Integrity","傳輸機密性與完整性",6,"保護傳輸資訊之機密性與完整性。"],
  ["SC-10","Network Disconnect","網路中斷",6,"在工作階段結束或閒置後終止網路連線。"],
  ["SC-11","Trusted Path","可信路徑",0,"建立可信通訊路徑。"],
  ["SC-12","Cryptographic Key Establishment and Management","密碼金鑰建立與管理",7,"建立並管理密碼金鑰。"],
  ["SC-13","Cryptographic Protection","密碼保護",7,"實施密碼保護。"],
  ["SC-15","Collaborative Computing Devices and Applications","協作運算裝置與應用",7,"禁止遠端啟動協作運算裝置。"],
  ["SC-16","Transmission of Security and Privacy Attributes","安全與隱私屬性傳輸",0,"將屬性與傳輸資訊關聯。"],
  ["SC-17","Public Key Infrastructure Certificates","公鑰基礎設施憑證",6,"依據憑證政策發行或取得公鑰憑證。"],
  ["SC-18","Mobile Code","行動程式碼",6,"定義並限制行動程式碼使用。"],
  ["SC-20","Secure Name/Address Resolution Service (Authoritative)","安全名稱/位址解析服務：權威來源",7,"提供來源鑑別與完整性驗證。"],
  ["SC-21","Secure Name/Address Resolution Service (Recursive/Caching)","安全名稱/位址解析服務：遞迴/快取",7,"對回應執行來源鑑別與完整性驗證。"],
  ["SC-22","Architecture for Name/Address Resolution Service","名稱/位址解析服務架構",7,"確保解析服務具容錯性。"],
  ["SC-23","Session Authenticity","工作階段真實性",6,"保護工作階段真實性。"],
  ["SC-24","Fail in Known State","以已知狀態失效",0,"在失效時以已知狀態失效。"],
  ["SC-25","Thin Nodes","精簡節點",0,"採用最小功能與資訊儲存。"],
  ["SC-26","Decoys","誘餌",0,"採用誘餌元件偵測惡意活動。"],
  ["SC-27","Platform-independent Applications","平台無關應用",0,"採用平台無關應用。"],
  ["SC-28","Protection of Information at Rest","靜態資訊保護",6,"保護靜態資訊。"],
  ["SC-29","Heterogeneity","異質性",0,"採用多樣化資訊技術。"],
  ["SC-30","Concealment and Misdirection","隱蔽與誤導",0,"採用隱蔽與誤導技術。"],
  ["SC-31","Covert Channel Analysis","隱匿通道分析",0,"執行隱匿通道分析。"],
  ["SC-32","System Partitioning","系統分割",0,"將系統分割至不同實體域。"],
  ["SC-34","Non-modifiable Executable Programs","不可修改之可執行程式",0,"從不可寫入媒體載入安全軟體。"],
  ["SC-35","External Malicious Code Identification","外部惡意程式碼識別",0,"含入探測元件偵測惡意程式碼。"],
  ["SC-36","Distributed Processing and Storage","分散式處理與儲存",0,"將處理與儲存分散至多個位置。"],
  ["SC-37","Out-of-band Channels","帶外通道",0,"採用帶外通道進行交付或傳輸。"],
  ["SC-38","Operations Security","作業安全",0,"採用作業安全保護措施。"],
  ["SC-39","Process Isolation","行程隔離",7,"為行程維護獨立執行域。"],
  ["SC-40","Wireless Link Protection","無線連結保護",0,"保護無線連結。"],
  ["SC-41","Port and I/O Device Access","連接埠與 I/O 裝置存取",0,"停用或移除連接埠或 I/O 裝置。"],
  ["SC-42","Sensor Capability and Data","感測器能力與資料",0,"禁止遠端啟動感測器能力。"],
  ["SC-43","Usage Restrictions","使用限制",0,"限制系統元件使用。"],
  ["SC-44","Detonation Chambers","引爆室/沙箱",0,"採用引爆室識別惡意程式碼。"],
  ["SC-45","System Time Synchronization","系統時間同步",6,"與權威時間來源同步。"],
  ["SC-46","Cross Domain Policy Enforcement","跨域政策執行",0,"實施跨域政策執行。"],
  ["SC-47","Alternate Communications Paths","替代通訊路徑",0,"建立替代通訊路徑。"],
  ["SC-48","Sensor Relocation","感測器重新配置",0,"重新配置感測器。"],
  ["SC-49","Hardware-enforced Separation and Policy Enforcement","硬體強制分離與政策執行",0,"實施硬體分離機制。"],
  ["SC-50","Software-enforced Separation and Policy Enforcement","軟體強制分離與政策執行",0,"實施軟體分離機制。"],
  ["SC-51","Hardware-based Protection","硬體基礎保護",0,"為韌體元件實施硬體保護。"],
  // ── SI ──
  ["SI-1","Policy and Procedures","政策與程序",15,"制定、記錄並傳達系統與資訊完整性政策及程序。"],
  ["SI-2","Flaw Remediation","漏洞修補",7,"識別、報告並矯正系統漏洞。"],
  ["SI-3","Malicious Code Protection","惡意程式碼保護",7,"實施惡意程式碼保護機制。"],
  ["SI-4","System Monitoring","系統監控",7,"監控系統以偵測攻擊。"],
  ["SI-5","Security Alerts, Advisories, and Directives","安全警報、諮詢與指令",7,"接收並傳播安全警報。"],
  ["SI-6","Security and Privacy Function Verification","安全與隱私功能驗證",4,"驗證安全與隱私功能。"],
  ["SI-7","Software, Firmware, and Information Integrity","軟體、韌體與資訊完整性",4,"偵測未授權變更。"],
  ["SI-8","Spam Protection","垃圾郵件保護",6,"採用垃圾郵件保護機制。"],
  ["SI-10","Information Input Validation","資訊輸入驗證",6,"驗證資訊輸入有效性。"],
  ["SI-11","Error Handling","錯誤處理",6,"產生安全的錯誤訊息。"],
  ["SI-12","Information Management and Retention","資訊管理與保留",15,"依法管理並保留資訊。"],
  ["SI-13","Predictable Failure Prevention","可預測失效預防",0,"提供替代元件預防失效。"],
  ["SI-14","Non-persistence","非持久性",0,"實施非持久性。"],
  ["SI-15","Information Output Filtering","資訊輸出過濾",0,"過濾系統輸出。"],
  ["SI-16","Memory Protection","記憶體保護",6,"保護系統記憶體。"],
  ["SI-17","Fail-safe Procedures","故障安全程序",0,"實施故障安全程序。"],
  ["SI-18","PII Quality Operations","個資品質作業",8,"檢查個資品質。"],
  ["SI-19","De-identification","去識別化",8,"移除個人可識別元素。"],
  ["SI-20","Tainting","污染標記",0,"嵌入污染標記以追蹤來源。"],
  ["SI-21","Information Refresh","資訊更新",0,"從可信來源更新資訊。"],
  ["SI-22","Information Diversity","資訊多樣性",0,"使用替代資訊來源。"],
  ["SI-23","Information Fragmentation","資訊碎片化",0,"對資訊進行碎片化處理。"],
  // ── SR ──
  ["SR-1","Policy and Procedures","政策與程序",7,"制定、記錄並傳達供應鏈風險管理政策及程序。"],
  ["SR-2","Supply Chain Risk Management Plan","供應鏈風險管理計畫",6,"制定供應鏈風險管理計畫。"],
  ["SR-3","Supply Chain Controls and Processes","供應鏈控制與流程",6,"建立降低供應鏈風險之流程。"],
  ["SR-4","Provenance","來源追溯",0,"記錄、監控並維護有效來源。"],
  ["SR-5","Acquisition Strategies, Tools, and Methods","取得策略、工具與方法",6,"採用取得策略以保護供應鏈。"],
  ["SR-6","Supplier Assessments and Reviews","供應商評估與審查",6,"評估並審查供應商風險。"],
  ["SR-7","Supply Chain Operations Security","供應鏈作業安全",0,"對供應鏈採用作業安全控制。"],
  ["SR-8","Notification Agreements","通知協議",6,"與供應商建立通知協議。"],
  ["SR-9","Tamper Resistance and Detection","防篡改抗性與偵測",0,"實施防篡改技術。"],
  ["SR-10","Inspection of Systems or Components","系統或元件檢查",0,"檢查系統或元件以偵測篡改。"],
  ["SR-11","Component Authenticity","元件真偽性",6,"實施反仿冒政策。"],
  ["SR-12","Component Disposal","元件處置",6,"處置資料、文件、工具或系統元件。"],
];

// Parse raw data into structured objects
export const CONTROLS = RAW.map(([id, name, nameTW, bl, desc]) => ({
  id,
  family: id.replace(/-\d+$/, ''),
  name,
  nameTW,
  baselines: { L: !!(bl & 1), M: !!(bl & 2), H: !!(bl & 4), P: !!(bl & 8) },
  desc,
}));

export const BASELINE_META = {
  L: { key: 'L', label: 'Low',      color: '#1e40af', bg: '#dbeafe', border: '#93c5fd' },
  M: { key: 'M', label: 'Moderate', color: '#92400e', bg: '#fef3c7', border: '#fbbf24' },
  H: { key: 'H', label: 'High',     color: '#9d174d', bg: '#fce7f3', border: '#f472b6' },
  P: { key: 'P', label: 'Privacy',  color: '#3730a3', bg: '#e0e7ff', border: '#a5b4fc' },
};
